[package]
name = "reticulum-tokio"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
reticulum-core = { path = "../reticulum-core", features = ["compression"] }
reticulum-node = { path = "../reticulum-node", features = ["compression"] }
reticulum-interface = { path = "../reticulum-interface" }
tokio = { version = "1", features = ["net", "io-util", "rt", "rt-multi-thread", "macros", "sync", "time"] }
getrandom = "0.2"
async-trait = "0.1"
if-addrs = "0.14"
socket2 = { version = "0.6", features = ["all"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
hex.workspace = true
